import { NextResponse } from "next/server";

export async function GET() {
  const orders = [
    {
      id: "1",
      orderId: "#CM9801",
      user: { name: "Natali Craig", avatar: "https://i.pravatar.cc/150?u=1" },
      project: "Landing Page",
      address: "Meadow Lane Oakland",
      date: "Just now",
      status: "In Progress",
    },
    {
      id: "2",
      orderId: "#CM9802",
      user: { name: "Kate Morrison", avatar: "https://i.pravatar.cc/150?u=2" },
      project: "CRM Admin pages",
      address: "Larry San Francisco",
      date: "A minute ago",
      status: "Complete",
    },
    {
      id: "3",
      orderId: "#CM9803",
      user: { name: "Drew Cano", avatar: "https://i.pravatar.cc/150?u=3" },
      project: "Client Project",
      address: "Bagwell Avenue Ocala",
      date: "1 hour ago",
      status: "Pending",
    },
    {
      id: "4",
      orderId: "#CM9804",
      user: { name: "Orlando Diggs", avatar: "https://i.pravatar.cc/150?u=4" },
      project: "Admin Dashboard",
      address: "Washburn Baton Rouge",
      date: "Yesterday",
      status: "Approved",
    },
    {
      id: "5",
      orderId: "#CM9805",
      user: { name: "Andi Lane", avatar: "https://i.pravatar.cc/150?u=5" },
      project: "App Landing Page",
      address: "Nest Lane Olivette",
      date: "Feb 2, 2023",
      status: "Rejected",
    },
    {
      id: "6",
      orderId: "#CM9806",
      user: { name: "Natali Craig", avatar: "https://i.pravatar.cc/150?u=1" },
      project: "Landing Page",
      address: "Meadow Lane Oakland",
      date: "Just now",
      status: "In Progress",
    },
    {
      id: "7",
      orderId: "#CM9807",
      user: { name: "Kate Morrison", avatar: "https://i.pravatar.cc/150?u=2" },
      project: "CRM Admin pages",
      address: "Larry San Francisco",
      date: "A minute ago",
      status: "Complete",
    },
    {
      id: "8",
      orderId: "#CM9808",
      user: { name: "Drew Cano", avatar: "https://i.pravatar.cc/150?u=3" },
      project: "Client Project",
      address: "Bagwell Avenue Ocala",
      date: "1 hour ago",
      status: "Pending",
    },
    {
      id: "9",
      orderId: "#CM9809",
      user: { name: "Orlando Diggs", avatar: "https://i.pravatar.cc/150?u=4" },
      project: "Admin Dashboard",
      address: "Washburn Baton Rouge",
      date: "Yesterday",
      status: "Approved",
    },
    {
      id: "10",
      orderId: "#CM9810",
      user: { name: "Andi Lane", avatar: "https://i.pravatar.cc/150?u=5" },
      project: "App Landing Page",
      address: "Nest Lane Olivette",
      date: "Feb 2, 2023",
      status: "Rejected",
    },
    {
      id: "11",
      orderId: "#CM9811",
      user: { name: "Orlando Diggs", avatar: "https://i.pravatar.cc/150?u=4" },
      project: "Admin Dashboard",
      address: "Washburn Baton Rouge",
      date: "Yesterday",
      status: "Approved",
    },
    {
      id: "12",
      orderId: "#CM9812",
      user: { name: "Andi Lane", avatar: "https://i.pravatar.cc/150?u=5" },
      project: "App Landing Page",
      address: "Nest Lane Olivette",
      date: "Feb 2, 2023",
      status: "Rejected",
    },
  ];
  return NextResponse.json(orders);
}
